-- USER SQL
CREATE USER "JAVA_DEV" IDENTIFIED BY "S0meStr0ngPassw0rd"  ;

-- QUOTAS
ALTER USER "JAVA_DEV" QUOTA UNLIMITED ON "DATA";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO "JAVA_DEV" ;
GRANT CREATE MATERIALIZED VIEW TO "JAVA_DEV" ;
GRANT CREATE VIEW TO "JAVA_DEV" ;
GRANT CREATE SESSION TO "JAVA_DEV" ;
GRANT CREATE TABLE TO "JAVA_DEV" ;
GRANT CREATE TYPE TO "JAVA_DEV" ;
GRANT CREATE PUBLIC DATABASE LINK TO "JAVA_DEV" ;
GRANT QUERY REWRITE TO "JAVA_DEV" ;
GRANT CREATE PUBLIC SYNONYM TO "JAVA_DEV" ;
GRANT CREATE SYNONYM TO "JAVA_DEV" ;
GRANT CREATE SEQUENCE TO "JAVA_DEV" ;
GRANT CREATE CLUSTER TO "JAVA_DEV" ;
GRANT PURGE DBA_RECYCLEBIN TO "JAVA_DEV" ;